name: VaultBox
options:
  bundleIdPrefix: com.vaultbox
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"

packages:
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios
    from: "5.0.0"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: "4.2.2"

targets:
  VaultBox:
    type: application
    platform: iOS
    sources:
      - path: VaultBox
    resources:
      - path: VaultBox/Resources
    settings:
      base:
        INFOPLIST_FILE: VaultBox/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vaultbox.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTED_INTERFACE_ORIENTATIONS: UIInterfaceOrientationPortrait
        SWIFT_STRICT_CONCURRENCY: complete
        CODE_SIGNING_ALLOWED: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: RevenueCat
        product: RevenueCat
      - package: KeychainAccess
    entitlements:
      path: VaultBox/VaultBox.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.vaultbox.app
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.security.application-groups:
          - group.com.vaultbox.app
        aps-environment: development

  VaultBoxTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: VaultBoxTests
    dependencies:
      - target: VaultBox
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vaultbox.app.tests

  VaultBoxUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: VaultBoxUITests
    dependencies:
      - target: VaultBox
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vaultbox.app.uitests

schemes:
  VaultBox:
    build:
      targets:
        VaultBox: all
        VaultBoxTests: [test]
        VaultBoxUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - VaultBoxTests
        - VaultBoxUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
